### ISSUE TITLE
Reference missing when compiling binding project?

### ISSUE THREAD

**Issue by ETHwsch** [TrekDev/Xamarin.Android.Skobbler#10]
I am facing compiling problems when compiling the binding project. The following items cannot be resovled:
- ISKSearchListener
- SKSearchResult
- SKSearchStatus

Thanks for help.
![skobbler-android](https://cloud.githubusercontent.com/assets/12100648/11450917/be1a3398-95b1-11e5-8808-c26e96026350.PNG)

**Comment by jeremy-ellis-tech** [comment]
Hi ETHwsch,

Sorry you're having problems building the project. Unfortunately I can't recreate the issue on my home or work machines from a clean clone, so any suggestions may be a shot in the dark.

Although, I have had a similar issue on another project recently: which was resolved by right clicking on the solution, cleaning, then rebuilding the project.

If that doesn't work, may I ask what version of Xamarin/Xamarin studio you're using? ~~I can't say I've tested everything yet with the new Xamarin/Xamarin studio versions.~~

I have tested on the latest version of Xamarin/Xamarin studio and it is working fine.

Thanks,

-TD

**Comment by ETHwsch** [comment]
Thanks for the feedback. It is strange that it works on your machine.
I am using Xamarin 5.10 on Mac and I build for Android 4.4.

Are you compiling on Windows and did you set specific compile options?

**I observed that a previous version of the binding project generated more binding information (See screen shot below) That's the reason for the compile errors. But it's hard to say what the root cause could be.**

![skobbler-generated](https://cloud.githubusercontent.com/assets/12100648/11452638/4f457b2e-95ef-11e5-81da-2dcff43b083e.PNG)

Best
ETHwsch

**Comment by jeremy-ellis-tech** [comment]
Thanks for the screenshots. Yes, I'm building on Windows, no specific compile options that aren't set in the csproj or Android Manifest. Unfortunately I don't have access to a Mac so I can't check if I can recreate the problem on one of those.

Do you have all the relevant Android SDKs installed/up to date? Off the top of my head I think you need to install via the Android SDK manager:
- Android SDK Tools
- Android SDK Platform Tools
- Android SDK Build-Tools
- Android 5.0.1 (API 21) SDK Platform and Google APIs
- Android 4.0.3 (API 15) SDK Platform and Google APIs
- Android Support Repository
- Android Support Library
- Google Play services.

**Comment by jeremy-ellis-tech** [comment]
Hi ETHwsch, did you manage to find a solution? May I close this issue if it's been resolved?

**Comment by ETHwsch** [comment]
Please wait for closing. We are investigating the issue and we will document the results here.

**Comment by ETHwsch** [comment]
The issues on Mac comes with Yosemite and Java 1.8.0_51 ! To downgrade issue the following command:
_sudo rm -rf /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk_
Then enter
_java -version_
And you will see java version _"1.7.0_85"_
Recompile the solution and the errors are gone.

**Comment by jeremy-ellis-tech** [comment]
Hi ETHwsch,

Glad you found a solution and thanks for reporting what was wrong. I'll add this note to the README at some point so others don't have to go through the same thing.

Thanks again!

TD
