### ISSUE TITLE
Calculating route error

### ISSUE THREAD

**Issue by DaveFCB** [TrekDev/Xamarin.Android.Skobbler#11]
When calculating route (via: com.skobbler.ngx.routing.SKRouteManager.calculateRouteWithPoints() by passing a list SKPostion objects consisting of  latitude and longitude values along with SKRouteSettings object) error occures: GPX track navigation is available for commercial use with a enterprise license and JNI DETECTED ERROR IN APPLICATION: jmethodID was NULL..... In new build of Skobbler SDK is it fixed: http://forum.skobbler.com/showthread.php/7563-Latest-2-5-1-Android-build ... Is there any possibility to use this build?

**Comment by jeremy-ellis-tech** [comment]
Hi @DaveFCB, thanks for letting me know. Will update asap.

**Comment by jeremy-ellis-tech** [comment]
@DaveFCB pushed a fix to the `develop` branch. If you can confirm it works for you I'll merge it into `master`.

**Comment by DaveFCB** [comment]
not working :-( the same error

**Comment by jeremy-ellis-tech** [comment]
~~@DaveFCB, I replaced the SKMaps.jar file and related documentation, so if it is still giving the same error it may not be related to that.~~

**Comment by jeremy-ellis-tech** [comment]
@DaveFCB, Ah, may have not changed the native libs. Hang on will try again.

**Comment by jeremy-ellis-tech** [comment]
@DaveFCB, Ok new native lib builds pushed. Let me know if that has solved it.

**Comment by DaveFCB** [comment]
Problem solved. Thanks a lot!

**Comment by jeremy-ellis-tech** [comment]
@DaveFCB Excellent. Thanks for letting me know.
