### ISSUE TITLE
Api_Key

### ISSUE THREAD

**Issue by andreluiz1987** [TrekDev/Xamarin.Android.Skobbler#12]
I do not quite understand, but do I have to have the map downloaded on the device?

**Comment by jeremy-ellis-tech** [comment]
What is the question? Are you talking about [assets](https://github.com/TrekDev/Xamarin.Android.Skobbler#assets)? If you're having an issue getting started, just look at the [demo project](https://github.com/TrekDev/Xamarin.Android.Skobbler/tree/master/src/Skobbler.SDKDemo).
