### ISSUE TITLE
Skobbler update 3.0.2

### ISSUE THREAD

**Issue by DaveFCB** [TrekDev/Xamarin.Android.Skobbler#13]
Hello,
is it possible to update Skobbler libraries to 3.0.2. Because there is problem with version of libpng. It is not possible to release app to the Google Play.

**Comment by jeremy-ellis-tech** [comment]
Hi Dave, I'll update it as soon as possible. Thanks for letting me know.

In the meantime you could checkout a previous version (tagged in git as `v2.5.1`, `v2.5.0` ...)

**Comment by jeremy-ellis-tech** [comment]
v3.0.2 pushed in d528a6e
