### ISSUE TITLE
Unable to get orientation sensor work in Navigation mode

### ISSUE THREAD

**Issue by ghost** [TrekDev/Xamarin.Android.Skobbler#3]
Hi TrekDev,

I'm trying to make the navigation arrow (in navigation mode) work with the orientation sensor. The route, directions and navigation are OK but the navigation arrow don't rotate. I tried different settings without success.
The orientation sensor is working great in route calculation, giving an accurate information using the orientation sensor.

Thank you for your time.

RA

**Comment by jeremy-ellis-tech** [comment]
Hi RA,

Is this with regards to the Sdk Demo or your own project?

-TD

**Comment by ghost** [comment]
Hello,

I'm using Sdk Demo.

RA

**Comment by jeremy-ellis-tech** [comment]
Hi RA,

Is this a bug with the current SDK demo or is this a feature you would like to add? I'm happy to help in both cases, just wondering what the context is.

-TD

**Comment by ghost** [comment]
Hello TrekDev,

Tbh, I don't know if it's a bug or "working as intended". I think that the navigation should contemplate the use of the orientation sensor by default (search the documentation and tried different options without any success). 

On the apk given in Android SDK I can't tell if it's being use or not because it's on simulation mode.

This app I'm developing is for offline-pedestrian use, so this is a must have feature. 

Thank you very much for your quick response!

RA

**Comment by jeremy-ellis-tech** [comment]
Ah ok. To be honest I have little experience with the navigation feature of the SDK beyond translating the simulation feature for the demo app, but I'm sure it could be done.

I'll start up a demo project. Can you post some code with what you have tried so far so I have a better idea of what we're looking for?

**Comment by jeremy-ellis-tech** [comment]
Hi RA,

After a bit of searching this might be more difficult than I thought!

I created a demo project and used navigation between points around my home-town. I'm pretty sure the rotation of the navigation icon is determined by the expected route you are taking and your last known positions over time, not the orientation of the phone. I've read through [the documentation](http://developer.skobbler.com/docs/android/2.3.0/index.html) and there is no mention of being able to override this behaviour, or even change the navigation icon drawable!

I then tried another project without using the navigation mode; using only markers and polylines. Unfortunately, it seems at this point you [can't rotate map markers](https://stackoverflow.com/questions/28288063/how-to-rotate-map-markers-with-skobbler) nor [indicate direction on polylines](https://stackoverflow.com/questions/28332263/how-to-indicate-direction-with-skobbler-polylines). You could probably use  `_mapView.ReportNewHeading(...);` for the default placement/heading icon, and add a `polyline` from a calculated route id via

```
var polyLine = new SKPolyline();
polyLine.Nodes = SKRouteManager.Instance.GetCoordinatesForRoute(id);
_mapView.AddPolyline(polyLine);
```

but unfortunately you would lose out on the niceties of the navigation mode.

Keep in mind I haven't spent that long researching this, but at this point I don't think this is a limitation of the C# bindings, but rather the Skobbler SDK itself, unfortunately. However, I might be completely wrong, so I would recommend [putting up a question on StackOverflow, with an `skmaps` & `android` tag](http://stackoverflow.com/questions/tagged/skmaps+android), or [trying to get in touch with the developers at Skobbler.](mailto:dev@skobbler.com)

As mentioned [here](http://stackoverflow.com/a/28338553/3715259), v2.4 of the Skobbler SDK is expected any day now. Hopefully this functionality will be included and I can update my bindings to let you guys use it.

-TD.

**Comment by ghost** [comment]
Hello TrekDev,

I did a lot of research about this option in the documentation and it seems to be a limitation indeed.

In this project, I just need a real time location with heading in the map for now (I'll use the rerouting to get the updates on time and distance left, giving a somewhat "navigation mode"). I'll keep an eye on the next SDK and your work for future updates!

Thank you very much for all your time and work! 

KR,
RA

**Comment by jeremy-ellis-tech** [comment]
Sorry I couldn't be of more help.

The good news is I've been in contact with the Skobbler team. v2.4 should be up this week and I should have the new bindings and SDK demo up over the weekend. Hopefully what you need will be in there.

I'll close this issue, but feel free to open another should you have any more problems with these, or the new bindings.

-TD

**Comment by jeremy-ellis-tech** [comment]
Hi RA,

Just to follow up with the SDK update. v2.4.0 has a lot of new code so I didn't manage to get it up to a point where I would be happy merging it back into the master branch, however, the actual SDK bindings should be OK. Most of the SDKDemo features are working but the new SDKTools library (which provides some helper classes/methods) needs a lot more work.

If you're feeling adventurous you can check them out on the `develop` branch and see if what you want is there.

-TD

PS. If you do decide to try out the develop branch, could you raise any issues you find? It would help me out a bunch since I can spend my time fixing them instead of finding them. Thanks :)
