### ISSUE TITLE
Skobbler sdk v 2.4

### ISSUE THREAD

**Issue by Dhanush-S** [TrekDev/Xamarin.Android.Skobbler#4]
Hi TrekDev,

Any plans on upgrading the bindings to Skobbler sdk v 2.4?

Regards,
Dhanush

**Comment by jeremy-ellis-tech** [comment]
Hi Dhanush,

I'm currently in the process of upgrading the SDK. You can checkout the `develop` branch and see how far I've got. Currently, the binding project should be OK to use, the main problem is the new SDK Tools project (not required to use the SDK, mostly helper classes), which just has a lot of new code and requires a bit of thought to translate it accurately into C#.

If you would like them done sooner you could checkout the `develop` branch and raise any issues you find in the new SDK Demo. It would be a big help for me so I can fix them as soon as I get the chance.

-TD
