### ISSUE TITLE
Unified API

### ISSUE THREAD

**Issue by sjchristi** [TrekDev/Xamarin.Android.Skobbler#6]
Hi TrekDev,

I was checking out your Android bindings, thank you so much for all the work.  I'm working on the iOS github bindings:

https://github.com/sjchristi/skobbler-mono-bindings

I am porting my app over to Android this month, and I would love to have a unified Skobbler Map SDK.  I'm not completely sure if/how this could be done, but I'm going to try.  I would love your help if you would be interested in working on this.

thanks!

**Comment by jeremy-ellis-tech** [comment]
Hi sj,

No problem. Thanks for your work too.

I'm not 100% sure how that could be done, since both SDKs are very "aware" of the platforms they run on (due to view-centric code). You might be able to pull out some very basic helper classes into a PCL, and maybe a thin interface layer, but I'm not sure how useful that would be.

What exactly did you have in mind?
- TD

**Comment by sjchristi** [comment]
TrekDev-

It may not be possible or just too much work, but I've seen other map APIs
like leaflet:

http://leafletjs.com/

that allow you to change the map source, and they work pretty well.  May
not be feasible, I'm still getting into the Android stuff so I'm not aware
of all the API differences..

The other bit of code we might share is all the code used to manage offline
maps.  I've already got a base implementation of this for iOS and I would
hope that at least this is similar on Android.

I'm working on an app right now that will include skobbler maps on both iOS
and Android, so maybe the best next steps are for me to continue working
and get a better idea for areas of code sharing/reuse.

thanks,
sam

**Comment by jeremy-ellis-tech** [comment]
Leafletjs isn't really comparable to Skobbler's native Android/iOS libraries though.

Unless you're talking about Skobbler's js/webmaps?

It is possible to share some basic logic in the SDKTools projects and then implement native interfaces for storage/etc, but again, it's a lot of work with not much benefit for the end user.
- TD
