### ISSUE TITLE
eglChooseConfig failed

### ISSUE THREAD

**Issue by sjchristi** [TrekDev/Xamarin.Android.Skobbler#7]
Just trying to run the demo project in the Xamarin Android Player.  I receive this error:

```
[eglCodecCommon] TcpStream::connect() - management hostname is 10.71.34.101
[eglCodecCommon] TcpStream::connect() - connecting host: 10.71.34.1
[AndroidRuntime] FATAL EXCEPTION: GLThread 91
[AndroidRuntime] Process: com.skobbler.sdkdemo, PID: 1216
[AndroidRuntime] java.lang.IllegalArgumentException: eglChooseConfig failed
[AndroidRuntime]    at com.skobbler.ngx.map.SKMultisampleConfigChooser.chooseConfig(SourceFile:54)
[AndroidRuntime]    at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
[AndroidRuntime]    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
[AndroidRuntime]    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by jeremy-ellis-tech** [comment]
Hi SJ,

What device are you emulating in the Android player? Have you tried it on a real device or the emulators provided with the Android SDK?

-TD

**Comment by sjchristi** [comment]
I'm using the Nexus 4 KitKat (v 4.4.2).  I haven't tried it on a real device (don't have one yet -doh!).  I'll try an emulator provided with Android SDK.  Do you know of any of the emulators in the Xamarin Android Player that should work?

thanks!
sam

**Comment by sjchristi** [comment]
I tried a nexus 4 4.4.2 on the packaged emulator with android SDK, and it gives me a different error:

```
[Choreographer] Skipped 44 frames!  The application may be doing too much work on its main thread.
[] HostConnection::get() New Host Connection established 0xb7ec2e90, tid 2538
[] HostConnection::get() New Host Connection established 0xb86014b0, tid 2579
[SKMaps] MapRenderer----@onSurfaceCreated
[Settings] Setting always_finish_activities has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
[SKMaps] MapRenderer----@onSurfaceCreated LinInitialized = true 
[SKMaps] MapRenderer---- @initGLView 
[SkobblerNG] set density JNI  - before NG_SetScreenScale 
[SkobblerNG] set density JNI  - after NG_SetScreenScale 
[SKMaps] MapRenderer----@onGLInitializationError called main
[SkobblerNG] NG_SetCCPIcon(12)
[SKMaps] MapRenderer----onSurfaceChanged width = 768 height= 1084
[SKMaps] MapRenderer----@onSurfaceCreated called main
[SKMaps] SKMapSurfaceView----Set map follower mode NONE
[mono-rt] 
[mono-rt] =================================================================
[mono-rt] Got a SIGSEGV while executing native code. This usually indicates
[mono-rt] a fatal error in the mono runtime or one of the native libraries 
[mono-rt] used by your application.
[mono-rt] =================================================================
[mono-rt] 
[libc] Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 2579 (Thread-93)
```

Do you know of a specific emulator version that it should work with?  I'll keep trying other stuff...

**Comment by jeremy-ellis-tech** [comment]
Hi Sj. I'm posting from my phone at the moment since I'm without a PC to verify all this so forgive me if its not totally correct.

I think the problem has to do with Xamarin Android Player being more of a simulator than a true emulator. Similarly if you check "use host GPU" when setting up your SDK emulator, you will get a more responsive emulator but you will run into problems like this when rendering glsurfaces.

My advice would be to use a real device or use the SDK emulators without any optimisations. Unfortunately they're slow but it's the only way to get accurate results without spending money on a device.

I'll be able to have a proper look this weekend and hopefully next week after I get my PC.

TD
