### ISSUE TITLE
Demo compilation error

### ISSUE THREAD

**Issue by marcioweck** [TrekDev/Xamarin.Android.Skobbler#8]
I tried to compile (VS2012) the sample, however I got the following error:
- with jdk-7-u79: "java.lang.VerifyError: Expecting a stackmap frame at branch target 36".

Maybe I'm using a wrong jdk version, but I also tried with java 6 and I got other error messages related with unsupported version.

Full build output (diagnostic mode):

>  C:\Program Files (x86)\Java\jdk1.7.0_79\bin\java.exe -jar "C:\Program Files (x86)\MSBuild\Xamarin\Android\jar2xml.jar" --jar=J:\git\Xamarin.Android.Skobbler\src\Skobbler.Binding\Jars\SKMaps.jar --ref="C:\Program Files (x86)\Android\android-sdk\platforms\android-19\android.jar" --out=J:\git\Xamarin.Android.Skobbler\src\Skobbler.Binding\obj\Debug\api.xml --ref=J:\git\Xamarin.Android.Skobbler\src\Skobbler.Binding\Jars\android-support-v4.jar --java7docpath=J:\git\Xamarin.Android.Skobbler\src\Skobbler.Binding\Jars\docs  (TaskId:47)
>  Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 36 (TaskId:47)
>  Exception Details: (TaskId:47)
>    Location: (TaskId:47)
>      com/skobbler/ngx/SKCategories$SKPOICategory.forInt(I)Lcom/skobbler/ngx/SKCategories$SKPOICategory; @11: if_icmpge (TaskId:47)
>    Reason: (TaskId:47)
>      Expected stackmap frame at this location. (TaskId:47)
>    Bytecode: (TaskId:47)
>      0000000: b802 2f59 4cbe 3d03 3e1d 1ca2 0019 2b1d (TaskId:47)
>      0000010: 3259 3a04 b402 2b1a a000 0619 04b0 8403 (TaskId:47)
>      0000020: 01a7 ffe8 b202 21b0                     (TaskId:47)
>   (TaskId:47)
>   at java.lang.Class.getDeclaredConstructors0(Native Method) (TaskId:47)
>   at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585) (TaskId:47)
>   at java.lang.Class.getDeclaredConstructors(Class.java:1906) (TaskId:47)
>   at jar2xml.JavaClass.doAppendToDocument(JavaClass.java:627) (TaskId:47)
>   at jar2xml.JavaClass.appendToDocument(JavaClass.java:559) (TaskId:47)
>   at jar2xml.JavaPackage.appendToDocument(JavaPackage.java:72) (TaskId:47)
>   at jar2xml.Start.main(Start.java:127) (TaskId:47)
> C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(253,5): error MSB6006: "java.exe" exited with code 1.
> Done executing task "JarToXml" -- FAILED. (TaskId:47)
> Done building target "ExportJarToXml" in project "Skobbler.Binding.csproj" -- FAILED.: (TargetId:22)

Regards,
Márcio Weck

**Comment by jeremy-ellis-tech** [comment]
Hi Márcio,

Thanks for opening this. Unfortunately I'm without an environment with a Xamarin license at the moment so I won't be able to test and/or put in immediate fixes.

However, some quick ideas off the top of my head: try checking out the `v2.3.0` tag, building with JDK 1.6 and see if the problem persists. Also, A quick search on stackoverflow came up with [this](https://stackoverflow.com/questions/15122890/java-lang-verifyerror-expecting-a-stackmap-frame-at-branch-target-jdk-1-7) which suggests using a `-noverify` flag in the java compilation flags. Again, I'm without a Xamarin license at the moment so can't test to see if it'll fix the problem but I'm happy to work this out as soon as I've got my license back.

Please let me know if that works, or gives you a different compilation error.

Thanks,

-TD

**Comment by marcioweck** [comment]
Hi TrekDev,

I solved it using `-noverify` after learn about problems related with java 7 and obfuscated libraries. I just append this option to `JavaOptions` variable. However, I'm not sure if I did it in the right place. I added this line to `Skobbler.Binding.csproj`:

> `<JavaOptions>$(JavaOptions) -noverify </JavaOptions>`

Thanks,

Márcio Weck

**Comment by jeremy-ellis-tech** [comment]
Hi Márcio,

That looks like the correct place to me. Glad you've managed to get it working. When I get my Xamarin license I'll look into adding this to the project.

Thanks,

TD
