### ISSUE TITLE
Change color of GPX Tracks plotting on map

### ISSUE THREAD

**Issue by Dhanush-S** [TrekDev/Xamarin.Android.Skobbler#9]
Hi TrekDev,

I have been trying to change the color of the GPX Track plotted on my map but with no luck.I looked into the documentation but did not get much info. Is there a way to change the color of the Tracks plotted in the map and if so can you please direct me as how to achieve the same?

Regards,
Dhanush

**Comment by jeremy-ellis-tech** [comment]
Hi Dhanush-S,

Have you seen [this post](http://stackoverflow.com/questions/25517924/how-to-change-the-color-of-the-route-in-skobbler) on StackOverflow? If you look into the assets folder of the SDK demo you'll see SKMaps.zip, which contains several style.json files. These contain the style attributes that define the colour of the GPX tracks.

The SO post mentions it isn't possible to change the route colour dynamically, if that is what you're after. However, it was answered nearly a year ago so it may have been added in v2.4, but I can't find anything about it in the documentation. It might be worth posting to the [Skobbler developer forums](http://forum.skobbler.com/), as the SDK developers are very active there and respond to developer requests frequently.

-TD

**Comment by jeremy-ellis-tech** [comment]
Hi Dhanush-S,

Skobbler SDK v2.5 has just been released today. I'm going to be updating the bindings over the next few days so hopefully it'll have what you're looking for.
- TD
